name: pr
on:
  push:
    branches:
      - "pull-request/[0-9]+"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pr-builder:
    needs:
      - check-nightly-ci
      - changed-files
      - checks
      - conda-java-tests
      - telemetry-setup
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@branch-25.10
    if: always()
    with:
      needs: ${{ toJSON(needs) }}
  telemetry-setup:
    continue-on-error: true
    runs-on: ubuntu-latest
    env:
      OTEL_SERVICE_NAME: 'pr-cuvs'
    steps:
      - name: Telemetry setup
        if: ${{ vars.TELEMETRY_ENABLED == 'true' }}
        uses: rapidsai/shared-actions/telemetry-dispatch-stash-base-env-vars@main
  check-nightly-ci:
    needs: telemetry-setup
    runs-on: ubuntu-latest
    env:
      RAPIDS_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check if nightly CI is passing
        uses: rapidsai/shared-actions/check_nightly_success/dispatch@main
        with:
          repo: cuvs
          max_days_without_success: 30
  changed-files:
    needs: telemetry-setup
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/changed-files.yaml@branch-25.10
    with:
      files_yaml: |
        test_java:
          - '**'
          - '!.devcontainer/**'
          - '!.pre-commit-config.yaml'
          - '!README.md'
          - '!docs/**'
          - '!img/**'
          - '!thirdparty/LICENSES/**'
  checks:
    needs: telemetry-setup
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/checks.yaml@branch-25.10
    with:
      enable_check_generated_files: false
      ignored_pr_jobs: "telemetry-summarize"
  conda-java-tests:
    needs: [conda-cpp-build, changed-files]
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/custom-job.yaml@branch-25.10
    if: fromJSON(needs.changed-files.outputs.changed_file_groups).test_java
    with:
      build_type: pull-request
      node_type: "gpu-l4-latest-1"
      arch: "amd64"
      container_image: "rapidsai/ci-conda:25.10-latest"
      script: "ci/test_java.sh"
      file_to_upload: "java/cuvs-java/target/"
  telemetry-summarize:
    # This job must use a self-hosted runner to record telemetry traces.
    runs-on: linux-amd64-cpu4
    needs: pr-builder
    if: ${{ vars.TELEMETRY_ENABLED == 'true' && !cancelled() }}
    continue-on-error: true
    steps:
      - name: Telemetry summarize
        uses: rapidsai/shared-actions/telemetry-dispatch-summarize@main
    env:
      GH_TOKEN: ${{ github.token }}
